-- CreateEnum
CREATE TYPE "SwarmWizardStep" AS ENUM ('DOMAIN_SETUP', 'REPOSITORY_SELECT', 'SWARM_CONFIG', 'DEPLOYMENT', 'COMPLETED');

-- CreateEnum
CREATE TYPE "StepStatus" AS ENUM ('PENDING', 'STARTED', 'PROCESSING', 'COMPLETED', 'FAILED');

-- AlterTable
ALTER TABLE "swarms" ADD COLUMN     "stepStatus" "StepStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN     "wizardData" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "wizardStep" "SwarmWizardStep" NOT NULL DEFAULT 'DOMAIN_SETUP';
