import {
  makeRes,
  createArtifact,
  ArtifactType,
  PYTHON_CODE,
  JSON_CODE,
} from "./helpers";

export function generateCodeResponse() {
  const messageId = Date.now().toString();

  return makeRes(
    "Perfect! I've created the connection leak monitor implementation. Here's what I've built:",
    [
      createArtifact({
        id: "code-artifact-1",
        messageId: messageId,
        type: ArtifactType.CODE,
        content: {
          file: "stakwork/senza-lnd/lib/connection_leak_monitor.rb",
          content: PYTHON_CODE,
          change: "Create main connection leak monitor class",
          action: "create",
        },
      }),
      createArtifact({
        id: "code-artifact-2",
        messageId: messageId,
        type: ArtifactType.CODE,
        content: {
          file: "stakwork/senza-lnd/config/database.json",
          content: JSON_CODE,
          change:
            "Add Aurora Postgres database configuration with connection leak monitoring settings",
          action: "create",
        },
      }),
    ]
  );
}

export function generateFormResponse() {
  const messageId = Date.now().toString();

  return makeRes(
    "I'll help you build a connection leak monitor. Here's my plan:",
    [
      createArtifact({
        id: "form-artifact-1",
        messageId: messageId,
        type: ArtifactType.FORM,
        content: {
          actionText:
            "Here's my plan to implement the connection leak monitor:",
          webhook: "https://stakwork.com/api/chat/confirm",
          options: [
            {
              actionType: "button",
              optionLabel: "✓ Confirm Plan",
              optionResponse: "confirmed",
            },
            {
              actionType: "button",
              optionLabel: "✗ Modify Plan",
              optionResponse: "modify",
            },
          ],
        },
      }),
    ]
  );
}

export function generateBrowserResponse() {
  const messageId = Date.now().toString();

  return makeRes("Here's a live preview of the Sphinx Chat community site:", [
    createArtifact({
      id: "browser-artifact-1",
      messageId: messageId,
      type: ArtifactType.BROWSER,
      content: {
        url: "https://community.sphinx.chat",
      },
    }),
  ]);
}

export function generateResponseBasedOnMessage(message: string) {
  const messageText = message.toLowerCase();

  if (messageText.includes("browser")) {
    return generateBrowserResponse();
  } else if (messageText.includes("code")) {
    return generateCodeResponse();
  } else if (messageText.includes("form")) {
    return generateFormResponse();
  } else if (messageText.includes("confirmed")) {
    return makeRes("Ok! Let's move forward with this plan");
  } else if (messageText.includes("modify")) {
    return makeRes("What do you want to modify?");
  } else {
    return makeRes("Autogenerated response.");
  }
}
